[package]
name = "acrust"
version = "0.1.0"
edition = "2021"

[dependencies]
cgmath = "0.18.0"
env_logger = "0.11.5"
gl = "0.14.0"
glfw = "0.58.0"
image = "0.25.5"
log = "0.4.22"
thiserror = "1.0.65"
cpal = "0.15.3"
rusttype = "0.9"
